version: '3'
services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
      args:
        username: admin
        password: password
        email: admin@admin.com
    image: server
  

  jxwaf:
    build:
      context: jxwaf
      dockerfile: Dockerfile
    image: jxwaf
