version: '3'
services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
      args:
        username: admin
        password: password
        email: admin@admin.com
    image: server
    ports:
    - 8000:8000
 
  

  jxwaf:
    build:
      context: jxwaf
      dockerfile: Dockerfile
    image: jxwaf
     ports:
    - 80:80
    - 443:443

  logstash:
    build:
      context: logstash
      dockerfile: Dockerfile
    image: logstash
    
